# Generated by Django 3.2.8 on 2021-10-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategories',
            new_name='SubCategory',
        ),
    ]
