# Generated by Django 3.2.8 on 2021-10-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0002_rename_subcategories_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categories_id',
            new_name='category',
        ),
    ]
