# Generated by Django 3.2.8 on 2021-11-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0003_rename_categories_id_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
