# Generated by Django 3.2.8 on 2021-10-26 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+8423456789'. Up to 15 digits allowed.", regex='^\\+?84?\\d{9,15}$')])),
                ('full_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('gateway', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
