# Generated by Django 3.2.8 on 2021-10-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotifications',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
    ]
