# Generated by Django 3.2.8 on 2021-11-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute_attribute_float_attribute_int_attribute_varchar_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
