# Generated by Django 3.2.8 on 2021-11-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('NAM', 'NAM'), ('NU', 'NU'), ('KHAC', 'KHAC')], default='NAM', max_length=100),
        ),
    ]
