# Generated by Django 3.2.8 on 2021-11-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
